# Application Configuration
spring:
   config:
      import: optional:configserver:http://localhost:8081
   application: 
      name: registry-services
   cloud:
      config:
         name: registry-services
         username: root
         password: s3cr3t
         fail-fast: false
   logging:
      level:
         com.votre.microservices: trace